-- -----------------------------------------------------
-- INSERT UF
-- -----------------------------------------------------
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (1, 'AC', 'ACRE');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (2, 'AL', 'ALAGOAS');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (3, 'AM', 'AMAZONAS');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (4, 'AP', 'AMAPÁ');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (5, 'BA', 'BAHIA');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (6, 'CE', 'CEARÁ');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (7, 'DF', 'DISTRITO FEDERAL');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (8, 'ES', 'ESPÍRITO SANTO');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (9, 'GO', 'GOIÁS');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (10, 'MA', 'MARANHÃO');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (11, 'MG', 'MINAS GERAIS');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (12, 'MS', 'MATO GROSSO DO SUL');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (13, 'MT', 'MATO GROSSO');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (14, 'PA', 'PARÁ');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (15, 'PB', 'PARAÍBA');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (16, 'PE', 'PERNAMBUCO');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (17, 'PI', 'PIAUÍ');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (18, 'PR', 'PARANÁ');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (19, 'RJ', 'RIO DE JANEIRO');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (20, 'RN', 'RIO GRANDE DO NORTE');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (21, 'RO', 'RONDÔNIA');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (22, 'RR', 'RORAIMA');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (23, 'RS', 'RIO GRANDE DO SUL');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (24, 'SC', 'SANTA CATARINA');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (25, 'SE', 'SERGIPE');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (26, 'SP', 'SÃO PAULO');
INSERT INTO public.UF (ID_ESTADO, UF, ESTADO_NOME) VALUES (27, 'TO', 'TOCANTINS');